using System.Text;
using MapsetVerifier.RankingCriteria.Model;
using MapsetVerifier.RankingCriteria.Parsing;

namespace MapsetVerifier.RankingCriteria.Sync;

/// <summary>
///     Writes the <c>RC</c> class of rule id constants. Checks reference these instead of raw strings, so a typo or a
///     retired statement becomes a compile error.
/// </summary>
public static class RcConstantsWriter
{
    public static string Write(RcSource source, IEnumerable<RcCataloguePage> pages)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine(
            "// Generated by MapsetVerifier.RankingCriteria.Tool from the ranking criteria catalogue."
        );
        builder.AppendLine(
            $"// Snapshot: {source.Repository}@{source.Commit}. Do not edit, run the tool instead."
        );
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("namespace MapsetVerifier.RankingCriteria;");
        builder.AppendLine();
        builder.AppendLine(
            "/// <summary> Ids of ranking criteria statements, for use with IssueTemplate.WithRule. </summary>"
        );
        builder.AppendLine("public static class RC");
        builder.AppendLine("{");

        var first = true;
        foreach (var cataloguePage in pages)
        {
            var page = RcPages.Get(cataloguePage.Page);
            var active = cataloguePage.Statements.Where(statement => !statement.IsRetired).ToList();
            if (page == null || active.Count == 0)
                continue;

            if (!first)
                builder.AppendLine();
            first = false;

            builder.AppendLine($"    /// <summary> {page.WikiUrl} </summary>");
            builder.AppendLine($"    public static class {page.ConstantsClass}");
            builder.AppendLine("    {");

            var usedNames = new HashSet<string>();
            foreach (var statement in active)
            {
                var name = UniqueName(ConstantName(statement), usedNames);
                usedNames.Add(name);

                builder.AppendLine(
                    $"        /// <summary> {statement.Upstream.Kind}: {Escape(statement.Upstream.Lead)} </summary>"
                );
                builder.AppendLine($"        public const string {name} = \"{statement.Id}\";");
            }

            builder.AppendLine("    }");
        }

        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary> "catch/salad/edge-dashes-not-used" → "Salad_EdgeDashesNotUsed". </summary>
    private static string ConstantName(RcStatement statement)
    {
        var parts = statement.Id.Split('/');
        var section = parts.Length > 2 ? RcText.PascalCase(parts[1]) : "";
        var slug = RcText.PascalCase(parts[^1]);
        var name = section.Length > 0 ? $"{section}_{slug}" : slug;

        return char.IsDigit(name[0]) ? "_" + name : name;
    }

    private static string UniqueName(string name, HashSet<string> usedNames)
    {
        if (!usedNames.Contains(name))
            return name;

        for (var suffix = 2; ; ++suffix)
            if (!usedNames.Contains($"{name}{suffix}"))
                return $"{name}{suffix}";
    }

    private static string Escape(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
